services:
  stats-server:
    build: stats_parent/stats-service
    image: explore-with-me-stats-parent
    container_name: stats-parent
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    volumes:
      - stats-db-data:/var/lib/postgresql/data


volumes:
  stats-db-data:

