server.port=9090

#spring.datasource.url=jdbc:postgresql://localhost:5432/stats
#spring.datasource.username=stats
#spring.datasource.password=stats

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info


